name: Test, Build, and Upload Binary

on:
  push:
    branches: [ main ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Run tests
        run: go test ./...

      - name: Build binary
        run: |
          go build -o external-proxy

      - name: Release with Notes
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: external-proxy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

